name: SonarCloud Analysis


on:
  push:
    branches: [ main, master ]
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  sonarqube:
    name: Run SonarQube Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Отключаем shallow clone для лучшего анализа

      - name: Set up Java (required for SonarScanner)
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: SonarQube Scan
        uses: SonarSource/sonarcloud-github-action@v1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
